### PR TITLE
Switch to SDL2

### PR DESCRIPTION
**Pull request by genpfault**
Outstanding issues:
* Breaks macOS & Windows builds; wasn't sure how to update them appropriately.
* Window title isn't (re)set on minimize; left a TODO.
* README.md is out of date re: dependencies for SDL2.

### CODE REVIEW

**Comment by mdsteele** [comment]
Hi, thanks for the PR!  I may be able to help with fixing the macOS and Windows builds.

Can you help me understand the motivation for this change, though?  I use SDL2 for new projects nowadays, but I think of Azimuth as already finished and working; are there existing issues that are fixed by upgrading Azimuth to SDL2?

**Comment by genpfault** [comment]
You bet, thank you for taking a look!

The major thing I'm trying to fix is that SDL1 completely mangles my KDE dual-monitor session on exit from fullscreen: it somehow manages to put the monitors in 'clone' mode and deletes one of the taskbars :(   And since SDL1 is pretty much a dead-end maintenance/feature-wise on the upstream side of things I doubt that'll get fixed anytime soon.

Additional features/improvements I was thinking of (not necessarily all in this PR):
* Single-implementation config path support via `SDL_GetPrefPath()`
* Single-implementation high-resolution timer via `SDL_GetPerformanceCounter()`
* HiDPI support via `SDL_GL_GetDrawableSize()`
* Non-4:3 resolution support via `glViewport()` & `glScissor()` letterboxing (have this one prototyped out, looks pretty spiffy at 1920x1200 :))

**Comment by mdsteele** [comment]
Gotcha, makes sense.  When I get a chance, I'll see if I can get the macOS build working.

**Comment by chekoopa** [comment]
Bump. Fullscreen mode for FullHD looks nasty, some remastering would be very cool.

**Comment by mdsteele** [comment]
Whoops, there goes a year and a half!  Sorry for dropping the ball on this.

I've just thrown together a draft [branch](https://github.com/mdsteele/azimuth/tree/sdl2) that brings this patch up to date and gets the SDL2 build working on Mac OS X, but I still need to make sure I didn't break things for other OSes before I merge it in.

**Comment by mdsteele** [comment]
Update: I've pushed some more changes to the [sdl2 branch](https://github.com/mdsteele/azimuth/tree/sdl2) that should fix the cross-compilation build for Windows, but I still need to verify that it actually runs correctly on a Windows machine.  I've also confirmed that that branch seems to build and run fine on both Debian and Mac OS X.

**Comment by mdsteele** [comment]
I've now confirmed that the cross-compiled Windows build works fine on a Windows machine, so I've gone ahead and merged in the [sdl2 branch](https://github.com/mdsteele/azimuth/tree/sdl2).  Thank you genpfault for the initial PR!

**Pull request merged**
